### ISSUE TITLE
Support Multipart File Upload

### ISSUE THREAD

**Issue by amaurymartiny** [feathersjs-ecosystem/feathers-blob#25]
### Steps to reproduce

- Upload a file with multipart upload
- Some previous logic needs to encode in base64 the uploaded file, something like: `const uri = dauria.getBase64DataURI(hook.params.file.buffer, hook.params.file.mimetype);`
- Call blobService.create like in Readme: `blobService.create({ uri }).then(...)`
- This service decodes again the `uri` into a buffer: https://github.com/feathersjs/feathers-blob/blob/master/src/index.js#L51

### Expected behavior

This seems like some unnecessary effort of encoding/decoding. Would be great that in the `create` method of the service, if `params.file.buffer` and `.mimetype` is set, then the body's `uri` is not needed anymore.

If both are set, then probably `uri` should take the priority.

### Actual behavior

N/A

### System configuration

Not relevant.

**Comment by claustres** [comment]
I think we can close this because it is now possible to send a raw buffer to the blob service and it is simple to retrieve the file buffer using a multipart file upload middleware like multer in the request and tranfer it with a hook.

**Comment by apmcodes** [comment]
It requires ```.contentType``` to be set else get error 

```
error: BadRequest: Buffer or URI with valid content type must be provided to create a blob
```

**Comment by claustres** [comment]
Yes as stated in the doc: https://github.com/feathersjs-ecosystem/feathers-blob#blobservicecreatebody-params.
