### ISSUE TITLE
How to resize an image before create it ? 

### ISSUE THREAD

**Issue by Johnba1988** [feathersjs-ecosystem/feathers-blob#35]
### Expected behavior
I want to resize image before create it and create two versions of my image (resized and original).

### System configuration
  feathers-blob :"^1.3.1"
**NodeJS version**:v8.4.0
**React Native Version**:"0.52.0"

**Comment by daffl** [comment]
[This part of the guide](https://docs.feathersjs.com/guides/advanced/file-uploading.html#feathers-blob-with-multipart-support) shows how to integrate multer. [Here](https://blog.ragingflame.co.za/2015/2/6/resizing-images-in-nodejs-applications) is a tutorial how to resize an image before uploading it with multer. In general, anything showing how to upload and resize files in Express should work for Feathers as well.

**Comment by Johnba1988** [comment]
@daffl  Thank you very much for your reply.

**Comment by claustres** [comment]
I think the issue has been answered, please reopen if required.
