### ISSUE TITLE
get() does not work with latest s3-blob-store (v3.0.0)

### ISSUE THREAD

**Issue by claustres** [feathersjs-ecosystem/feathers-blob#37]
Worked well with previous version (v2.1.0) so do not upgrade.

See https://github.com/jb55/s3-blob-store/issues/17.

**Comment by claustres** [comment]
Seems to be corrected now but we need to upgrade the version in our tests to be sure before closing the issue.

**Comment by daffl** [comment]
Since Greenkeeper is enabled on this repository, it should have verified that tests are still passing so I think we're good.
