### ISSUE TITLE
feathers client resolves to service path instead of store model on get and remove

### ISSUE THREAD

**Issue by mcchrish** [feathersjs-ecosystem/feathers-blob#4]
This code won't work on the `feathers-client`:

``` js
// Assuming `file.txt` exists.

// NotFound: Page not found
app.service('/blob').remove('file.txt')
```

It would try to find `<host>/blob/file.txt` (Which is the service path) instead of the real location of the store, e.g. S3, FS.

**Comment by daffl** [comment]
`id` is the result id you get during creation with

```js
blobService.create(blob).then(function (result) {
  console.log('Stored blob with id', result.id);
}).catch(err => {
  console.error(err);
});
```

I don't think it is the filename is it?

**Comment by mcchrish** [comment]
It depends now. It could be specified in the request through `id` property otherwise it would default to `${hash}.${extension}`.
Strangely, the service methods are working as expected if used immediately (before adding all the middleware and listening to a port).

**Comment by daffl** [comment]
That does sound like a bug. Could you set up an example to reproduce the issue?

**Comment by ekryski** [comment]
bump @mcchrish. Do you have an example by chance?

**Comment by mcchrish** [comment]
Sorry for the very late response.
Just got here a quick example.
https://github.com/mcchrish/feathers-blob/tree/blob-test

So what I found out that if the name of the files is simply `test.txt` without the directory, it will successfully delete the file. However, if it's in a directory like `files/test.txt` it won't.

**Comment by ekryski** [comment]
@mcchrish pefect that helps out a lot.

**Comment by MHerszak** [comment]
I have the same problem as @mcchrish. It works if used immediately but not if you dispatch an action later. I am getting this error `TypeError: Cannot read property 'before' of undefined` coming from ` getHooks (/Users/michelherszak/Projects/javascript/calo-beta/node_modules/feathers-hooks/lib/commons.js:84:37)`. I can't locate the error but I assume it comes from service 'upload' since it never occurred before.

**Comment by claustres** [comment]
This issue is pretty old and tests have been updated to include also a feathers client test.
