### ISSUE TITLE
Extension can be ".false" if mime type is not recognized

### ISSUE THREAD

**Issue by andys8** [feathersjs-ecosystem/feathers-blob#47]
### Issue

There is conversion between mimeType and extension. It can be the case, that it's not working as intended, when the mimeType is not recognized correctly.

The used library, can actually return `false`.

Used here:
https://github.com/feathersjs-ecosystem/feathers-blob/blob/10a01e9f7dfc810015c0362d5982fb0d48351e69/lib/index.js#L70

Source in lib `mime-types` returning `false`:
https://github.com/jshttp/mime-types/blob/master/index.js#L107-L123

This will lead to ids ending with `.false`.

#### Goal

I'm thinking about if the implementation can not work without recognizing the mime type at all.

* It would probably make sense to not have the extension ".false" and leave it out, if the implementation is still working.
* The create method should fail early and raise an error, if it doesn't make sense to store the file without mimetype/extension.

#### Additional information

The changes have to stay in sync with other code, using mimeTypes or extensions.

Usage of `mimeTypes.lookup`:
https://github.com/feathersjs-ecosystem/feathers-blob/blob/10a01e9f7dfc810015c0362d5982fb0d48351e69/lib/index.js#L38

#### Type definitions of mime-types api

```ts
// Type definitions for mime-types 2.1
// Project: https://github.com/jshttp/mime-types#readme
// Definitions by: Gyusun Yeom <https://github.com/Perlmint>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

export function lookup(filenameOrExt: string): string | false;
export function contentType(filenameOrExt: string): string | false;
export function extension(typeString: string): string | false;
export function charset(typeString: string): string | false;
export const types: {[key: string]: string};
export const extensions: {[key: string]: string[]};
```

**Comment by claustres** [comment]
I think we should raise an error if the mime type is not recognized or automatically switch to application/octet-stream as RFC2046 says "The "octet-stream" subtype is used to indicate that a body contains arbitrary binary data" and drop the extension as you propose.

**Comment by andys8** [comment]
The library in use - `dauria` - would use `application/octet-stream'` by default: https://github.com/Mithgol/dauria/blob/master/dauria.js#L21
But this is not working if the argument is set to `false`.

Would be a valid solution for me. Could probably fall back to `.bin` as extension instead of dropping it.

**Comment by lagmanzaza** [comment]
I got the same problem. I try to upload Image by using React Native then file store that has `.false` extension
