### ISSUE TITLE
Add TypeScript definitions

### ISSUE THREAD

**Issue by savy-91** [feathersjs-ecosystem/feathers-blob#78]
### Steps to reproduce

- Create a new feathers project with typescript
- try to import `import BlobService from 'feathers-blob';`

### Expected behavior
It should import the module without issues

### Actual behavior
I get the following error:

> Could not find a declaration file for module feathers-blob'. '*' implicitly has an 'any' type.   Try `npm install @types/feathers-blob` if it exists or add a new declaration (.d.ts) file containing `declare module 'feathers-blob';

**Comment by claustres** [comment]
Please could you test if it's fine following closing of https://github.com/feathersjs-ecosystem/feathers-blob/pull/79 ? thanks

**Comment by Mairu** [comment]
The typings will only be available in a new version (or when you use git to fetch the module).

**Comment by savy-91** [comment]
Hi and thanks a lot! I'll make sure to test it asap

**Comment by abrain** [comment]
> The typings will only be available in a new version (or when you use git to fetch the module).

Using the latest version from git resolves the TypeScript error for me.

**Comment by daffl** [comment]
This has been done via https://github.com/feathersjs-ecosystem/feathers-blob/pull/79

**Comment by abrain** [comment]
> This has been done via #79

Would it be possible to publish this in a release?

**Comment by daffl** [comment]
Odd, I don't know why it hasn't been. Done now.

**Comment by abrain** [comment]
👍 thanks!
