### ISSUE TITLE
Use filename in new hash

### ISSUE THREAD

**Issue by MarcGodard** [feathersjs-ecosystem/feathers-blob#89]
In my system, if 2 people upload the same file with different file names, I would like the blob to save it twice. Is this possible?

**Comment by claustres** [comment]
I am not sure why it would not be already possible. If you worry about the default behavior, which generates an ID as a content hash, you can simply bypass it by providing the `id` on the create operation (e.g. a uuid).

**Comment by MarcGodard** [comment]
Ahhh thanks, didn't know that was possible.
