### ISSUE TITLE
[Question] Data uri VS Raw data buffer

### ISSUE THREAD

**Issue by victor-gabou** [feathersjs-ecosystem/feathers-blob#95]
Hello,

Not a bug here :)

I was just wondering what are the difference between using data uri or raw data buffer

I've been using feathers-blob for several years and as I always used the [feathers doc](https://docs.feathersjs.com/cookbook/express/file-uploading.html#basic-upload-with-feathers-blob-and-feathers-client) when starting a project, I've used data uri every times.

But as I'm starting a new project, I wonder if raw data buffer is better (or worst) than data uri and what are the pros and cons.

My main concern is performances.

Thanks for your work!

**Comment by claustres** [comment]
Maybe another difference is about the protocol which is best adapted to both approach. When using websocket you don't really have any problem to transfer a big buffer but when using raw HTTP it can be more complicated and requires multipart upload, which might be more easy to deal with using data URI. However I am not sure about that as you can use a blob with a raw buffer in a multipart upload.

**Comment by victor-gabou** [comment]
Thanks a lot for these informations!

To sum up, as I'm working on a generic file input, the best would be to return files as data uri as it's more convenient with a rest approach (and not problematic with sockets) + it allows me to display selected files (if images) directly before submitting them to server.
For the file download case, as it's not complicated to transform data uri to blob on client I don't think that I should take this into consideration.

Does this sound like the right approach to you?

**Comment by claustres** [comment]
That's exactly what I am doing actually, so it sounds good to me ;-)

**Comment by victor-gabou** [comment]
Perfect, thanks for your replies :)
